### ISSUE TITLE
In MKT potential, India overall total value not matched with the overall state value

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#103]
Check the screenshot,

![screenshot-github com-2018 12 18-16-17-34](https://user-images.githubusercontent.com/44860646/50149177-788dce80-02e0-11e9-89ca-5feddcf97d73.png)

**Comment by guganbrandidea** [comment]
Resolved population mismatch in country and state level.

**Comment by VigneshBI** [comment]
As per developer comment, closed this issue
