### ISSUE TITLE
In MKT Potential---> SEC HHs, The system is loading but didn't get the result when I choosing the "By Qrtr / By Year". please show the appropriate warning message. 

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#106]
Check the screenshot,

![screenshot-github com-2018 12 19-12-27-40](https://user-images.githubusercontent.com/44860646/50204020-6a47bd00-0389-11e9-988d-7108c231a3c4.png)

**Comment by guganbrandidea** [comment]
Resolved

**Comment by VigneshBI** [comment]
This is fixed.
