### ISSUE TITLE
In Tertiary sales, By Year (2017) total results are not matched with By Qrtr(2017). please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#110]
Check the screenshot,

![screenshot-github com-2018 12 19-18-45-15](https://user-images.githubusercontent.com/44860646/50222425-36d35580-03be-11e9-8ae9-91f60a096587.png)

**Comment by guganbrandidea** [comment]
Year,Quarter and Month value won't match, because data given separately for each one.

**Comment by VigneshBI** [comment]
This is fixed.
