### ISSUE TITLE
In Secondary sales --> Diagnostics --> All commodity volm %,  the system is loading but I didn't get the result when I choosing the 2014 & 2015 years. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#114]
Check the screenshot,

![image](https://user-images.githubusercontent.com/44860646/50279824-dcdf9800-0470-11e9-870f-e25da07f548c.png)

**Comment by SaranyaBI** [comment]
We don't have category consumption for 2014 and 2015.
So, we removed in timeline.

**Comment by VigneshBI** [comment]
Ok

**Comment by VigneshBI** [comment]
Ok
