### ISSUE TITLE
In Secondary sales --> Diagnostics --> Uncovered outlet, I didn't get the draw radius result in the map. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#115]
Check the screenshot,

![screenshot-app grammarly com-2018 12 20-16-43-43](https://user-images.githubusercontent.com/44860646/50281681-49a96100-0476-11e9-9a00-628509596c47.png)

**Comment by SaranyaBI** [comment]
1. Radius - SEC HHS will work
2. Radius - LSM HHs will work

3. Radius - Shampoo Potential by LSM & 4. Radius - shampoo Potential by SEC  functionality created for demo purpose only, so won't work.

**Comment by VigneshBI** [comment]
This is fixed.
