### ISSUE TITLE
In hulka --> secondary sales, I didn't get the result in Sub-distt. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#122]
Check the screenshot,

![screenshot-github com-2018 12 21-15-16-13](https://user-images.githubusercontent.com/44860646/50336177-71123380-0533-11e9-9db1-c49fc8001b47.png)

**Comment by SaranyaBI** [comment]
Need to install new build.

**Comment by VigneshBI** [comment]
This is fixed.
