### ISSUE TITLE
In Secondary sales-->Diagnostics--> Category Share (%), By Year(2018)  total results are not matched with By Qrtr / By month(2018). please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#123]
Check the screenshot,

![image](https://user-images.githubusercontent.com/44860646/50338098-50e57300-0539-11e9-8995-8eb0c21abe08.png)

**Comment by SaranyaBI** [comment]
Updated April month in 2018 timeline.

**Comment by VigneshBI** [comment]
This is fixed.
