### ISSUE TITLE
In MKT potential --> profild indvdls, didn't get the result in village map view. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#127]
Check the screenshot,

![image](https://user-images.githubusercontent.com/44860646/50342335-98bfc680-0548-11e9-9508-9658a99d5c18.png)

**Comment by guganbrandidea** [comment]
Its available only for calendar year...placed alert for quarter and month

**Comment by VigneshBI** [comment]
This is fixed
