### ISSUE TITLE
In Secondary sales-->Diagnostics--> Category Share (%), I didn't get the result when I choosing the Category Share (%). please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#150]
Check the screenshot,

![gs](https://user-images.githubusercontent.com/44860646/50400173-ae342b00-07aa-11e9-8375-42bfd07c34b2.png)

**Comment by SaranyaBI** [comment]
Completed

**Comment by VigneshBI** [comment]
This is fixed.
