### ISSUE TITLE
 In Secondary sales --> Sales --> Split (By Retailer-valuer), Empty detail page is shown when I selecting the "Radius- Shampoo Potential by LSM, Radius- Shampoo Potential by SEC". please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#156]
Check the screenshot,

![tw](https://user-images.githubusercontent.com/44860646/50475751-c0e97280-09eb-11e9-83ad-a737ed573d33.png)

**Comment by SaranyaBI** [comment]
We did for demo purpose only. removed in online version.

**Comment by VigneshBI** [comment]
This is fixed
