### ISSUE TITLE
In Secondary sales, Distributor name is not available when I choosing the "Split-By Distrbtr". Is it correct? 

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#158]
Check the screenshot,

![screenshot-github com-2018 12 28-11-51-sad](https://user-images.githubusercontent.com/44860646/50505643-f305dd80-0a9a-11e9-9c3e-42fc1988783c.png)

**Comment by SaranyaBI** [comment]
Completed

**Comment by VigneshBI** [comment]
This is fixed.
