### ISSUE TITLE
In Karnataka --> Chitradurga Distt --> Chitradurga sub-distt --> Chitradurga city, Back button missing in Chitradurga city map

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#283]
Check the screenshot,

![image](https://user-images.githubusercontent.com/44860646/52949552-9b049c80-33a2-11e9-8902-960ab1e42df8.png)

**Comment by guganbrandidea** [comment]
Map Issue

**Comment by VigneshBI** [comment]
This is fixed
