### ISSUE TITLE
In Karnataka --> Udupi Distt --> Udupi sub-distt --> Udupi city, Back button missing in Udupi city map. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#284]
Check the screenshot,

![va](https://user-images.githubusercontent.com/44860646/52950233-80cbbe00-33a4-11e9-9c7e-da24e17e9a66.png)

**Comment by guganbrandidea** [comment]
Map Issue By Saravanan

**Comment by VigneshBI** [comment]
This is fixed.
