### ISSUE TITLE
In Rajasthan --> Tonk Distt., --> Tonk Sub-distt., Tonk town missing in Tonk Sud-distt. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#285]
Check the screenshot,

![mna](https://user-images.githubusercontent.com/44860646/52953079-73b2cd00-33ac-11e9-8baa-aa98122e3d05.png)

**Comment by guganbrandidea** [comment]
Map Issue By Saravanan

**Comment by VigneshBI** [comment]
This is fixed.
