### ISSUE TITLE
In Tamil Nadu -->  Vellore Distt., --> Vellore Sub-distt., Vellore city map not loaded properly. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#286]
Check the screenshot,

![notlo](https://user-images.githubusercontent.com/44860646/52954177-7b27a580-33af-11e9-909a-5070a1fc91f9.png)

**Comment by guganbrandidea** [comment]
Map Issue By Amudhan

**Comment by VigneshBI** [comment]
This is fixed.
