### ISSUE TITLE
In Tamil Nadu --> Tiruvannamalai Distt., --> Tiruvannamalai Sub-distt., Back button not working in Tiruvannamalai Sub-distt. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#288]
Check the screenshot,

![bathi](https://user-images.githubusercontent.com/44860646/52993256-9939e800-3439-11e9-8c68-84c9ed0b0a94.png)

**Comment by guganbrandidea** [comment]
Map issue fixed by saravanan

**Comment by VigneshBI** [comment]
This is fixed.
