### ISSUE TITLE
In Uttar Pradesh --> Unnao Distt. --> Unnao Sub-distt. -->Unnao City, Click option not available in Unnao City. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#289]
Check the screenshot,

![cck](https://user-images.githubusercontent.com/44860646/52994660-59293400-343e-11e9-9df1-9addb28c63c9.png)

**Comment by guganbrandidea** [comment]
Map Issue By Amudhan

**Comment by VigneshBI** [comment]
This is fixed.
