### ISSUE TITLE
In Uttar Pradesh --> Hathras distt. --> Hathras sub-distt., Hathras city map not loaded properly. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#290]
Check the screenshot,

![notloaded](https://user-images.githubusercontent.com/44860646/52996529-eae77000-3443-11e9-9e12-61714d6df65d.png)

**Comment by guganbrandidea** [comment]
Map issue

**Comment by VigneshBI** [comment]
This is fixed.
