### ISSUE TITLE
In NBFC --> MKT potential --> Dealer Network, TVS name shown in Dealer network. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#297]
Check the screenshot,

![tvsc](https://user-images.githubusercontent.com/44860646/53070284-a8d23300-3504-11e9-8439-f09b48390691.png)

**Comment by AmudhanBI** [comment]
All Company will come in Mkt potntl

**Comment by VigneshBI** [comment]
Okay.
