### ISSUE TITLE
In Godrej --> Air freshner, MKT Potential category consumption value mismatched with Secondary sales. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#320]
Check the screenshot,

![air](https://user-images.githubusercontent.com/44860646/53473061-7178fe80-3a8f-11e9-83c6-2082cab1d35e.png)

**Comment by guganbrandidea** [comment]
Id Error, fixed by amudhan

**Comment by VigneshBI** [comment]
This is fixed.
