### ISSUE TITLE
In Punjab --> Amritsar distt. --> Baba Bakala sub-distt --> Rayya Town, Back button missing in n'brhd map. please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#343]
Check the screenshot,

![fs](https://user-images.githubusercontent.com/44860646/53859930-5bc28680-4005-11e9-808e-8cd786637951.png)

**Comment by sa6avanan** [comment]
Done

**Comment by VigneshBI** [comment]
This is fixed.
