### ISSUE TITLE
In Punjab --> Patiala distt. --> Nabha Sub-distt. --> Map not loaded properly in Nabha town. Please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#352]
Check the screenshot,

![nabha](https://user-images.githubusercontent.com/44860646/54019514-60c43900-41b1-11e9-943c-0aecec9c6b3a.png)

**Comment by sa6avanan** [comment]
Done

**Comment by VigneshBI** [comment]
This is fixed.
