### ISSUE TITLE
In Punjab --> Amritsar distt. -->Patti sub-distt --> Khemkaran Town, Back button missing in n'brhd map. please check it 

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#358]
Check the screenshot,

![image](https://user-images.githubusercontent.com/44860646/54181674-4fd33a80-44c5-11e9-8939-71f18642a67e.png)

**Comment by sa6avanan** [comment]
Done

**Comment by VigneshBI** [comment]
This is fixed.
