### ISSUE TITLE
In P&G MKT Potential --> category consumption(Rs.), "By Cal Yr" consumption value mismatched with "By month". please check it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#429]
Check the screenshot,

![image](https://user-images.githubusercontent.com/44860646/57673227-d4167b00-7638-11e9-9e3e-eabf8c7f7ba1.png)

**Comment by guganbrandidea** [comment]
need to move online

**Comment by VigneshBI** [comment]
Fixed
