### ISSUE TITLE
In Meghalaya -->E. Khasi Hills distt., -->Mawphlang subdistt map not loading. pls fix it

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#437]
check the screenshot,

![image](https://user-images.githubusercontent.com/44860646/58306931-c328ef00-7e1a-11e9-81a6-20a1fc069df1.png)

**Comment by AmudhanBI** [comment]
It's working properly.





VigneshBI <notifications@github.com> 
05/24/2019 11:55 AM
Please respond to
VigneshBI/New 
<reply@reply.github.com>


To
VigneshBI/New <New@noreply.github.com>
cc
AmudhanBI <amudhan@brandidea.com>, Assign <assign@noreply.github.com>
Subject
Re: [VigneshBI/New] In Meghalaya -->E. Khasi Hills distt., -->Mawphlang 
subdistt map not loading. pls fix it (#437)






Assigned #437 to @AmudhanBI.

**Comment by VigneshBI** [comment]
fixed
