### ISSUE TITLE
In Meghalaya--> E. Garo Hills, didn't get the result when I changing the toggle map view (distt- town, distt- vills, distt- town/villg ).

### ISSUE THREAD

**Issue by VigneshBI** [VigneshBI/New#440]
Check the screenshot,

![image](https://user-images.githubusercontent.com/44860646/58309132-f2425f00-7e20-11e9-8094-a0d1e6cf62e9.png)

**Comment by guganbrandidea** [comment]
saravanan fixed the map issue.

**Comment by VigneshBI** [comment]
This is fixed.
